version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - inventomate-network

  python-api:
    build: .
    container_name: python-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - inventomate-network

networks:
  inventomate-network:
    driver: bridge
    name: inventomate-network
