apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fedesimone31@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: fedesimone31@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: 5878375eb036a88ce8d063a2905d5083aced9
        selector:
          dnsZones:
            - "inventomate.xyz"
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-dev-cloudflare
  namespace: inventomate
spec:
  secretName: nginx-default-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "inventomate.xyz"
  dnsNames:
  - "inventomate.xyz"