apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fedesimone31@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: fedesimone31@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: NcABmzmORZSzjkG8gOq4qM9ONIrZHCmWpWWbSSJF
        selector:
          dnsZones:
            - "inventomate.xyz"