apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - 35.227.28.109
    secretName: tls-secret
  rules:
  - host: 35.227.28.109
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-inventomate
            port:
              number: 5173