apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  # Servidor de producción de Let's Encrypt
    email: fedesimone31@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-private-key  # Nombre del secreto que contiene la clave privada para Let's Encrypt en producción
    solvers:
      - http01:
          ingress:
            class: nginx