apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: inventomate
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        args: []
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"  # Permite el acceso sin contraseña para root
        - name: MYSQL_ROOT_HOST
          value: "%"  # Permite acceso desde cualquier host (puedes limitarlo según necesites)
        - name: MYSQL_DATABASE
          value: bd-inventomate
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: init-mysql
---
# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: inventomate
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
