---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-dev-cloudflare
  namespace: istio-system
spec:
  secretName: nginx-default-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "inventomate.xyz"
  dnsNames:
  - "inventomate.xyz"

