# spring-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-inventomate
spec:
  selector:
    matchLabels:
      app: spring-inventomate
  template:
    metadata:
      labels:
        app: spring-inventomate
    spec:
      containers:
      - name: spring-inventomate
        image: simondileogit/spring-inventomate:${{ github.sha }}
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: OKTA_OAUTH2_ISSUER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: OKTA_OAUTH2_ISSUER
        - name: OKTA_OAUTH2_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: OKTA_OAUTH2_AUDIENCE
        - name: CLIENT_ORIGIN_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLIENT_ORIGIN_URL
        - name: AUTH0_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH0_DOMAIN
        - name: AUTH0_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH0_CLIENT_SECRET
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: URL_DATABASE
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_DATABASE
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PASSWORD_DATABASE
        - name: DATABASE_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_CONNECTION
        - name: MELI_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_ACCESS_TOKEN
        - name: MELI_APP_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_APP_ID
        - name: MELI_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_CLIENT_SECRET
        - name: MELI_CODE_LOGIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_CODE_LOGIN
        - name: MELI_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_REDIRECT_URI
        - name: MELI_REFRESH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MELI_REFRESH_TOKEN
        - name: EMAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_PASSWORD
        - name: EMAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_USERNAME
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URI
        - name: FLASK_URL_BASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_URL_BASE
---
# spring-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-inventomate
spec:
  ports:
  - port: 8080
  selector:
    app: spring-inventomate
