# spring-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-inventomate
  namespace: inventomate
spec:
  selector:
    matchLabels:
      app: spring-inventomate
  template:
    metadata:
      labels:
        app: spring-inventomate
    spec:
      containers:
      - name: spring-inventomate
        image: simondileogit/spring-inventomate:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        envFrom:
            - configMapRef:
                name: app-config
        
---
# spring-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-inventomate
  namespace: inventomate
  annotations:
    #cloud.google.com/neg: '{"ingress": true}'
    #service.beta.kubernetes.io/azure-load-balancer-resource-group: myResourceGroup
    cloud.google.com/load-balancer-ipv4: "34.148.152.120"
spec:
  type: LoadBalancer
  loadBalancerIP: 34.148.152.120
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    app: spring-inventomate
